Hw2 node js
MasterWork1995/nodejs-homework-restAPI pull request #2
Opened 2021-10-31 16:19 UTC by MasterWork1995

Vlad, please check my homework and tell me what I need to update

2021-11-02 01:22 UTC, TViglesGoom requested changes

2021-11-02 01:22 UTC, TViglesGoom commented on models/contacts/addContact.js
> +const id = crypto.randomBytes(16).toString('hex')
У вас так у всех новых объектов будет одинаковый айдишник (честно признаюсь, не запускал, но компилятор в моей голове подсказывает). Так что проверьте. Как проверите, отпишите результат.

2021-11-02 01:22 UTC, TViglesGoom commented on models/contacts/getById.js
> +  const contact = contacts.find((item) => item.id.toString() === id.toString())
Зачем на каждой итерации цикла кастить обе переменный к строке? Мы не знаем, какой там тип данных лежит? И оба они, к тому не, ещё и не числа и не строки, видимо, а абсолютно разные типы данных, раз оба к строке кастим

2021-11-02 01:22 UTC, TViglesGoom commented on models/contacts/onCorrectId.js
> +}
Это только в `dev` версии будет консоль барикодировать? Или и в продакшине тоже?

2021-11-02 01:22 UTC, TViglesGoom commented on models/contacts/removeById.js
> +    (contact) => contact.id.toString() === id.toString()
Чёрный ящик, а не айдишник, прям

2021-11-02 01:22 UTC, TViglesGoom commented on models/contacts/updateById.js
> +  const index = contacts.findIndex((item) => item.id.toString() === id)
О, а тут уже только один приводим

2021-11-02 01:22 UTC, TViglesGoom commented on models/contacts/updateById.js
> +    return onCorrectId()
Нейминг. Во-первых, нет глагола в названии. Метод - что-то делает. А это у нас глаголы.
Во-вторых. А точно на on correct id? Maybe on incorrect id?

2021-11-02 01:22 UTC, TViglesGoom commented on routes/api/contacts.js
> +  name: Joi.string().min(3).max(30).required(),
Ян вышел из чата. Боюсь, не могли люди предвидеть, что имя в пасспорте может стать ограничением для регистрации в сервисе, если о нём забудут

2021-11-02 01:22 UTC, TViglesGoom commented on routes/api/contacts.js
> +    const { error } = joiShema.validate(req.body)
Советую, для валидации сделать middleware. Такой мощный и классный механизм!

2021-11-02 01:22 UTC, TViglesGoom commented on routes/api/contacts.js
> +      throw new BadRequest(error.message)
Создаём ошибку, чтобы тут же её отловить? Вы не первый такой. Далеко...
Это вас так учат? Или в интернете нашли?

2021-11-03 21:27 UTC, MasterWork1995 commented on models/contacts/addContact.js
> +const id = crypto.randomBytes(16).toString('hex')
провірив, завжди різні ід приходять

2021-11-03 21:28 UTC, MasterWork1995 commented on models/contacts/getById.js
> +  const contact = contacts.find((item) => item.id.toString() === id.toString())
змінив джейсон і переправив ід на строки

2021-11-03 21:34 UTC, MasterWork1995 commented on models/contacts/onCorrectId.js
> +}
видалив повністю цю функцію

2021-11-03 21:35 UTC, MasterWork1995 commented on models/contacts/removeById.js
> +    (contact) => contact.id.toString() === id.toString()
пофіксив

2021-11-03 21:35 UTC, MasterWork1995 commented on models/contacts/updateById.js
> +  const index = contacts.findIndex((item) => item.id.toString() === id)
пофіксив)))

2021-11-03 21:36 UTC, MasterWork1995 commented on models/contacts/updateById.js
> +    return onCorrectId()
видалив функцію, повертаю просто null

2021-11-03 21:36 UTC, MasterWork1995 commented on routes/api/contacts.js
> +  name: Joi.string().min(3).max(30).required(),
виправив мін 1 символ

2021-11-03 21:37 UTC, MasterWork1995 commented on routes/api/contacts.js
> +    const { error } = joiShema.validate(req.body)
зробив мідлвар

2021-11-03 21:37 UTC, MasterWork1995 commented on routes/api/contacts.js
> +      throw new BadRequest(error.message)
так вчили

2021-11-06 11:26 UTC, merged