Auth
MasterWork1995/nodejs-homework-restAPI pull request #4
Opened 2021-11-17 20:13 UTC by MasterWork1995

Hi Vlad, pls check the homework and if all is OK approve PR. Thanks!

2021-11-20 20:07 UTC, KirillKulakow commented on controllers/auth/login.js
> +  //   }
я думаю это можно удалить

2021-11-20 20:07 UTC, KirillKulakow commented on controllers/auth/login.js
> +// const { NotFound, Unauthorized } = require('http-errors')
эти комменты тоже можно удалить

2021-11-20 20:08 UTC, KirillKulakow commented on controllers/auth/register.js
> +  // const hashPassword = bcrypt.hashSync(password, bcrypt.genSaltSync(10))
думаю все закомментированое можно удалить

2021-11-20 20:15 UTC, KirillKulakow commented on controllers/contacts/getAll.js
> +  const { page = 0, limit = 0, favorite } = req.query
- все что приходит в query всегда будет с типом строка, favorite же в схеме должен быть в булевом типе
- хорошо было бы сделать проверку всех параметров page и limit на валидное число, а над favorite нужно подумать какие два вида нужны для определения true или false

2021-11-20 20:19 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
если сделаю запрос на список контактов без авторизации - приложение сломается

2021-11-20 20:20 UTC, KirillKulakow commented on models/user.js
> +  hashPassword: /^\$2[ayb]\$.{56}$/,
=) не пойму зачем паттерн на хэш пароль)

2021-11-20 20:22 UTC, KirillKulakow requested changes
Need fix

2021-11-21 08:48 UTC, MasterWork1995 reviewed
fixed!

2021-11-21 08:48 UTC, MasterWork1995 commented on controllers/auth/login.js
> +// const { NotFound, Unauthorized } = require('http-errors')
на майбутнє для себе залишив

2021-11-21 08:48 UTC, MasterWork1995 commented on controllers/auth/login.js
> +  //   }
на майбутнє для себе залишив

2021-11-21 08:48 UTC, MasterWork1995 commented on controllers/auth/register.js
> +  // const hashPassword = bcrypt.hashSync(password, bcrypt.genSaltSync(10))
на майбутнє для себе залишив

2021-11-21 08:48 UTC, MasterWork1995 commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
не получається мені відтворити це цомусь

2021-11-21 08:48 UTC, MasterWork1995 commented on models/user.js
> +  hashPassword: /^\$2[ayb]\$.{56}$/,
Думав, типу перевірка що попав іменно хеш пароль а не інший. Видалив

2021-11-21 08:48 UTC, MasterWork1995 commented on controllers/contacts/getAll.js
> +  const { page = 0, limit = 0, favorite } = req.query
не дуже зрозумів що потрібно зробити?

2021-11-21 10:05 UTC, KirillKulakow approved these changes

2021-11-21 10:19 UTC, merged