Avatar
MasterWork1995/nodejs-homework-restAPI pull request #5
Opened 2021-11-27 13:29 UTC by MasterWork1995

2021-11-27 19:01 UTC, KirillKulakow commented on controllers/auth/register.js
> +  const avatarURL = gravatar.url(email)
нужно добавить опцию протокола

2021-11-27 19:03 UTC, KirillKulakow commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
хорошо бы сделать вариацию на MIME тип входящего файла

2021-11-27 19:03 UTC, KirillKulakow requested changes
Need fix

2021-11-28 13:53 UTC, MasterWork1995 commented on controllers/auth/register.js
> +  const avatarURL = gravatar.url(email)
добавив

2021-11-28 13:53 UTC, MasterWork1995 commented on middlewares/upload.js
> +  filename: (req, file, cb) => {
добавив

2021-11-28 16:16 UTC, MasterWork1995 commented
fix

2021-11-28 21:53 UTC, KirillKulakow approved these changes

2021-11-28 23:09 UTC, merged